name: Publish Coverage Report

on:
  push:
    branches:
      - main

jobs:
  build-test-and-publish-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore MyMath/MyMath.sln

      - name: Build solution
        run: dotnet build MyMath/MyMath.sln --configuration Release --no-restore

      - name: Run tests with coverage
        run: |
          dotnet test MyMath/MyMath.sln --configuration Release --no-build --collect:"XPlat Code Coverage"
          mkdir -p coverage
          reportgenerator -reports:"MyMath/**/coverage.cobertura.xml" -targetdir:coverage -reporttypes:Html

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage

      - name: Deploy coverage report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: coverage
          destination_dir: cobertura